### ISSUE TITLE
Input de pesquisa num local pouco acessível ou inapropriado

### ISSUE THREAD

**Issue by Creuma-Kuzola** [e200/developers.ao#5]
Olá. @e200. Espero que esteja tudo bem contigo.
Primeiramente, meus parabéns pelo projecto...

Quando entrei no site estive a procura do input de pesquisa. Pensei que não tivesse, mas depois fui ao icone de menu e notei que estava lá. Não creio que seja o local mais acessível. Sugiro que esteja posicionado nos locais habituais, já que se trata duma funcionalidade primária e não de uma secundária.

**Comment by e200** [comment]
Verdade. Já alguém havia tocado nesse aspecto e eu mesmo sabia desse problema quando concebi a interface, mas não tenho muito tempo livre. Preferi fazer o que estava ao meu alcance, e estou a contar com a ajuda de quem estiver disponível para cobrir os buracos encontrados no projecto.

Vou corrigir o problema no futuro quando tiver tempo, mas se puder, sinta-se livre corrigir e mandar um pull-request! Obrigado :)

**Comment by e200** [comment]
Feito.

Espero que esteja minimamente aceitável agora. Qualquer questão é só reabrir a issue, e muito obrigado pela contribuição. :)

**Comment by Creuma-Kuzola** [comment]
> Feito.
> 
> Espero que esteja minimamente aceitável agora. Qualquer questão é só reabrir a issue, e muito obrigado pela contribuição. :)

De nada, Eleandro! :)
